@startuml

actor Developer as dev

node PC {
  frame Docker {
    [nginx] as nginx
    frame Application {
      [websh_server] as server
      [websh_remover] as remover
    }
    [shellgeibot] as bot
  }
  [file_system] as fs
}

dev -down-> nginx : POST http://localhost/api/shellgei
nginx -> server : proxy
server -> bot : POST
server -down-> fs : write file
bot -> fs : write file
remover -> fs : remove file

@enduml
