@startuml

actor Developer as dev

node PC {
  package Docker {
    [nginx] as nginx
    frame Application {
      [websh_server] as server
      [websh_remover] as remover
    }
    [shellgeibot] as bot
  }
  [file_system] as fs
}

dev -down-> nginx : POST http://localhost/api/shellgei
nginx -down-> server : proxy
server -left-> bot : POST
server -down-> fs : read / write file
bot -> fs : write file
remover -> fs : remove file

@enduml
