@startuml

actor User as user
boundary ブラウザ as web
boundary GitHub as gh
boundary APIアプリ as api
boundary Docker as docker

activate api
activate gh
user -> web : トップページにアクセス
activate user
activate web
web -> gh : HTML取得
gh -> web : HTML返却
web -> user : 画面表示

user -> web : シェル芸の入力
user -> web : Postボタンをクリック
web -> api : POST /api/shellgei 
api -> docker : docker run
activate docker
docker -> docker : シェルの実行
docker -> api : 実行結果の返却
deactivate docker
api -> web : 実行結果の返却
web -> user : 画面表示
deactivate user
deactivate web

@enduml
